-- Postgres port of schema.sql. Same spine: influencers → posts → calls → marks,
-- plus wallet_events → contradictions.
--
-- ⚠️ This file and `schema.sql` must describe the SAME shape. They are kept in
-- lockstep by `tests/schema-parity.test.ts`, which compares column names table by
-- table — a column added to one and not the other is exactly the failure that took
-- the deployed app down on 2026-08-18 (ERRORS.md §R), one dialect over.
--
-- Deliberate type choices, so the application code does NOT have to change:
--   * `synthetic` / `verified` stay INTEGER 0/1 rather than becoming BOOLEAN. Every
--     query and component compares them numerically; switching to a real boolean
--     would be a wider, riskier diff than the storage saving is worth.
--   * Unix seconds stay INTEGER. They are read as numbers everywhere and fit int4
--     until 2038; a timestamptz column would change every comparison in the app.
--   * REAL → DOUBLE PRECISION (Postgres REAL is 4-byte and would silently round
--     prices and confidences).
--   * `id` is GENERATED BY DEFAULT (not ALWAYS) so the SQLite import can supply
--     explicit ids; `scripts/migrate-to-postgres.ts` resets each sequence afterwards.

CREATE TABLE IF NOT EXISTS influencers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  handle TEXT UNIQUE NOT NULL,
  platform TEXT NOT NULL DEFAULT 'x',
  display_name TEXT,
  -- Self-disclosed only (HANDOFF.md §2.2). Set together or not at all.
  wallet_address TEXT,
  disclosure_source_url TEXT,
  verified_by TEXT,
  avatar_url TEXT,
  CHECK ((wallet_address IS NULL) = (disclosure_source_url IS NULL))
);

CREATE TABLE IF NOT EXISTS posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  influencer_id INTEGER NOT NULL REFERENCES influencers(id),
  platform_post_id TEXT UNIQUE NOT NULL,
  content TEXT NOT NULL,
  -- keccak256 of the canonical post text: what FCE-A signs over and FCE-B recomputes.
  content_hash TEXT NOT NULL,
  url TEXT NOT NULL,
  posted_at INTEGER NOT NULL,
  deleted_at INTEGER,
  raw_json TEXT,
  classified_at INTEGER,
  -- 1 when invented by seed-demo.ts. Load-bearing for honesty: the UI only links
  -- identifiers to public explorers for real rows.
  synthetic INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS calls (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id INTEGER UNIQUE NOT NULL REFERENCES posts(id),
  template TEXT NOT NULL CHECK (template IN ('DIRECTIONAL', 'TARGET_CALL', 'GEM_SHILL', 'AMBIGUOUS')),
  asset_symbol TEXT,
  feed_id TEXT,
  direction TEXT CHECK (direction IN ('long', 'short')),
  target_price DOUBLE PRECISION,
  expiry_at INTEGER,
  confidence DOUBLE PRECISION NOT NULL,
  -- Raw model output, shown beside the source post (HANDOFF.md §2.4). Never scored.
  extraction_json TEXT,
  status TEXT NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'settled', 'unpriceable', 'ambiguous', 'contradicted'))
);

-- Marks are retention, not cache: each row keeps the anchor-feed body and its Merkle
-- proof so a price can prove itself on-chain long after the fact.
CREATE TABLE IF NOT EXISTS marks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id INTEGER NOT NULL REFERENCES calls(id),
  kind TEXT NOT NULL CHECK (kind IN ('entry', 'latest', 'bench_entry', 'bench_latest')),
  feed_id TEXT NOT NULL,
  voting_round_id INTEGER NOT NULL,
  value INTEGER NOT NULL,
  decimals INTEGER NOT NULL,
  price_usd DOUBLE PRECISION NOT NULL,
  proof_json TEXT NOT NULL,
  proven_tx TEXT,
  marked_at INTEGER NOT NULL,
  UNIQUE (call_id, kind)
);

-- One row per call: the FDC attestation of the source, and the two chained TEE
-- signatures (FCE-A over the post, FCE-B over the extraction).
CREATE TABLE IF NOT EXISTS attestations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id INTEGER UNIQUE NOT NULL REFERENCES calls(id),
  fdc_request_bytes TEXT,
  fdc_voting_round_id INTEGER,
  fdc_proof_json TEXT,
  fdc_verified_tx TEXT,
  source_tee_signature TEXT,
  source_tee_signer TEXT,
  extraction_tee_signature TEXT,
  extraction_tee_signer TEXT,
  verified INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS wallet_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  influencer_id INTEGER NOT NULL REFERENCES influencers(id),
  tx_hash TEXT NOT NULL,
  asset_symbol TEXT,
  token_address TEXT NOT NULL,
  side TEXT CHECK (side IN ('buy', 'sell')),
  usd_value DOUBLE PRECISION,
  occurred_at INTEGER NOT NULL,
  synthetic INTEGER NOT NULL DEFAULT 0,
  UNIQUE (tx_hash, token_address, side)
);

CREATE TABLE IF NOT EXISTS contradictions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id INTEGER NOT NULL REFERENCES calls(id),
  wallet_event_id INTEGER NOT NULL REFERENCES wallet_events(id),
  gap_hours DOUBLE PRECISION NOT NULL,
  UNIQUE (call_id, wallet_event_id)
);

-- One row per confirmed copy/fade. No users/allocations model: HANDOFF.md §2.3
-- forbids standing delegation, so there is no stored authority.
CREATE TABLE IF NOT EXISTS executions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id INTEGER NOT NULL REFERENCES calls(id),
  mode TEXT NOT NULL CHECK (mode IN ('copy', 'fade')),
  xrpl_account TEXT NOT NULL,
  xrpl_tx_hash TEXT UNIQUE,
  direction TEXT NOT NULL CHECK (direction IN ('long', 'short')),
  fxrp_amount TEXT,
  flare_tx_hash TEXT,
  nonce TEXT,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'executed', 'failed')),
  reason TEXT,
  created_at INTEGER NOT NULL,
  synthetic INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_posts_influencer ON posts (influencer_id, posted_at);
CREATE INDEX IF NOT EXISTS idx_marks_call ON marks (call_id);
CREATE INDEX IF NOT EXISTS idx_wallet_events_influencer ON wallet_events (influencer_id, occurred_at);
